deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: random-wheel/
  target_branch: master
  language: node_js
  node_js: 14
  cache: yarn
  on:
    branch: master